#############################
## Image Classifier Config ##
#############################

# 选择默认模式，目前有 AspectRatio 和 Threshold 两种模式
# AspectRatio：通过横纵比来对图像进行分类。当图像的横纵比超过设定的阈值时，则移动到设置的对应的文件夹内，否则移动到 Other 文件夹
# Threshold：通过设置横纵分辨率的最低阈值来对图像进行分类
Mode: "AspectRatio"

# 完成一次分类后的暂停时间
# 如果磁盘性能较低，可设置为更高的值，默认为 0.05（单位 second）
Delay: "0.05"


#############################
## AspectRatio 模式配置文件 ##
#############################

# AspectRatioSourceFolder：AspectRatio 模式的源文件夹
AspectRatioSourceFolder: "./AspectRatio/Source"

# LandscapeFolder：当图片被判断为横向图片时，输出的目标文件夹
LandscapeFolder: "./AspectRatio/Landscape"

# PortraitFolder：当图片被判断为纵向图片时，输出的目标文件夹
PortraitFolder: "./AspectRatio/Portrait"

# OtherFolder：当图片既不是横向也不是纵向时，输出的目标文件夹
OtherFolder: "./AspectRatio/Other"

# W2H_Threshold：判断图片横纵的阈值，默认为 1.2
W2H_Threshold: "1.2"



###########################
## Threshold 模式配置文件 ##
###########################

# Threshold 模式的源文件夹
ThresholdSourceFolder: "./Threshold/Source"

# PortraitMinWidth：纵向图片的最小宽度阈值，若低于此值，则移动到 Destination 文件夹(单位 pixel)
PortraitMinWidth: "1080"

# PortraitMinHeight：纵向图片的最小高度阈值，若低于此值，则移动到 Destination 文件夹(单位 pixel)
PortraitMinHeight: "2400"

# LandscapeMinWidth：横向图片的最小宽度阈值，若低于此值，则移动到 Destination 文件夹(单位 pixel)
LandscapeMinWidth: "2560"

# LandscapeMinHeight：横向图片的最小高度阈值，若低于此值，则移动到 Destination 文件夹(单位 pixel)
LandscapeMinHeight: "1440"

# TargetFolder：移动的目标文件夹
TargetFolder: "./Threshold/Target"



###########################
## Extension 模式配置文件 ##
###########################

# Extension 模式的源文件夹
ExtensionSourceFolder: "./Extension/Source"

# PNG 目标文件夹
PNGTarget: "./Extension/PNG"

# JP(E)G 目标文件夹
JPGTarget: "./Extension/JPG"

# WebP 目标文件夹
WebPTarget: "./Extension/WebP"

# BMP 目标文件夹
BMPTarget: "./Extension/BMP"